
# environment
org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# minecraft
minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.22)
parchment_mappings_version=2024.11.17
neo_version=21.1.145
neo_version_range=[21.1.0,)
loader_version_range=[4,)

# dependencies
create_version=6.0.4-53
ponder_version=1.0.46
flywheel_version=1.0.2
registrate_version=MC1.21-1.3.0+62

# optionals
jei_version=19.21.0.247
curios_version=9.2.2


# mechano
mod_id=mechano
mod_version=0.1.0
mod_group_id=com.quattage.mechano

mod_name=Mechano
mod_authors=quat
mod_description=Bringing Create's polish to other mods.
mod_license=MIT