
# environment
org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false


# minecraft
minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.22)
parchment_mappings_version=2024.11.17
neo_version=21.1.194
neo_version_range=[21.1.0,)
loader_version_range=[4,)

# dependencies
ejml_version=0.42

create_version=6.0.6-98
ponder_version=1.0.59
flywheel_version=1.0.4
registrate_version=MC1.21-1.3.0+62

# optionals
jei_version=19.21.0.247
spark_version=1.10.142-SNAPSHOT
jol_version=0.9


# mechano
mod_id=mechano
mod_version=0.1.2
mod_group_id=com.quattage.mechano

mod_name=Mechano
mod_authors=quat
mod_description=Bringing Create's polish to other mods.
mod_license=MIT