
modLoader = "javafml"
loaderVersion = "[0,)"
issueTrackerURL = "https://github.com/quattage/mechano/issues"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://github.com/quattage/mechano"
logoFile = "logo.png"
logoBlur = false
credits = ""
authors = "${mod_authors}"
description = '''${mod_description}'''

[[mixins]]
config = "${mod_id}.mixins.json"

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "[${neo_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "create"
type = "required"
versionRange = "[6.0.10,)"
ordering = "NONE"
side = "BOTH"
