name: Build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup JDK 21
      run: echo "JAVA_HOME=$JAVA_HOME_21_X64" >> "$GITHUB_ENV"

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-read-only: false

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run Gametests
        run: ./gradlew runGameTestServer